ScreenManager:
    Window1:
    Window2:
    Login:
    Registration:
    Recipes:
    Pantry:

<Pantry>:
    name:"pantry"

    MDLabel:
        id: no_more_stink
        pos_hint: {'center_x':0.85, 'center_y':0.6}
        text: "Pantry Screen"

    MDRectangleFlatButton:
        text: "please, let me leave..."
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        on_press: root.manager.current = 'window1'
        on_press: root.manager.transition.duration = 0.25


<Recipes>:
    name:"recipes"

    MDLabel:
        id: no_more_stink
        pos_hint: {'center_x':0.85, 'center_y':0.6}
        text: "Recipes Screen"

    MDRectangleFlatButton:
        text: "please, let me leave..."
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        on_press: root.manager.current = 'window1'
        on_press: root.manager.transition.duration = 0.25


<Registration>:
    name:"registration"

    MDLabel:
        id: no_more_stink
        pos_hint: {'center_x':0.85, 'center_y':0.6}
        text: "Registration Screen"

    MDRectangleFlatButton:
        text: "please, let me leave..."
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        on_press: root.manager.current = 'window1'
        on_press: root.manager.transition.duration = 0.25

<Login>:
    name:"login"

    MDLabel:
        id: no_more_stink
        pos_hint: {'center_x':0.85, 'center_y':0.6}
        text: "Login Screen"

    MDRectangleFlatButton:
        text: "please, let me leave..."
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        on_press: root.manager.current = 'window1'
        on_press: root.manager.transition.duration = 0.25

<Window1>:
    name: "window1"
    test: no_more_stink

    MDLabel:
        id: no_more_stink
        pos_hint: {'center_x':0.85, 'center_y':0.6}
        text: "Welcome Window"

    MDRectangleFlatButton:
        text: "Login!"
        pos_hint: {'center_x':0.5, 'center_y':0.5}
        on_press: root.manager.current = 'login'

    MDRectangleFlatButton:
        text: "Register"
        pos_hint: {'center_x':0.5, 'center_y':0.4}
        on_press: root.manager.current = 'registration'

    MDRectangleFlatButton:
        text: "No Thanks"
        pos_hint: {'center_x':0.5, 'center_y':0.3}
        on_press: root.manager.current = 'window2'

<Window2>:
    name: "window2"
    container: container
         
    MDBoxLayout:
        orientation: "vertical"
        spacing: "10dp"


    ScrollView:
        scroll_timeout: 100

        MDList:
            id: container
            padding:0

    
    MDFloatingActionButtonSpeedDial: #floating list button
        id:float_button
        callback: self.parent.call_back
        data: app.sm.get_screen("window2").data
        root_button_anim: True
        #rotation_root_button : True #this breaks the whole thing
        hint_animation: True

    NavigationLayout:
        ScreenManager:
            Screen:
                BoxLayout:
                    orientation: 'vertical'

                    MDToolbar:
                        title: "Yung Money -- The List"
                        elevation: 10
                        left_action_items: [['menu', lambda x: nav_drawer.set_state()]]

                    Widget:
        
        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer:
                id: content_drawer


<ItemDrawer>:
    theme_text_color: "Custom"
    on_press: self.parent.parent.set_state("close")
    on_press: self.parent.parent.parent.parent.parent.current = "window1" #this is ugly but it works

    IconLeftWidget:
        id: icon
        icon: root.icon
        theme_text_color: "Custom"
        text_color: root.text_color


<ContentNavigationDrawer>: #All of the info in the nav drawer
    orientation: "vertical"
    padding: "8dp"
    spacing: "8dp"

    AnchorLayout:
        anchor_x: "left"
        anchor_y: "top"
        size_hint_y: None
        height: avatar.height

        Image: #User image, not necessary but could be cool. Current Captain Wheeze
            id: avatar
            size_hint: None, None
            size: "56dp", "56dp"
            source: "CaptainWheezeopp.png"

    MDLabel: # This will eventually be the username of the user
        text: app.user.username
        font_style: "Button"
        size_hint_y: None
        height: self.texture_size[1]

    MDLabel: # and this will be the users email
        text: app.user.email
        font_style: "Caption"
        size_hint_y: None
        height: self.texture_size[1]

    ScrollView: #This is the nav list in the navbar, probably doesn't need a scrollview
    
    DrawerList:
        id: md_list




<SwipeItem>:

    size_hint_y: 1
    height: content.height
    pos_hint: {"center_x": 0.5, "center_y": 0.5}

    MDCardSwipeLayerBox:
        padding: "8dp"

        MDIconButton:
            icon: "trash-can"
            pos_hint: {"center_y": 0.5}
            on_release: self.parent.parent.parent.parent.parent.remove_item(root)

        MDIconButton:
            icon: "database-plus"
            pos_hint: {"center_y": 0.5}
            on_release: self.parent.parent.parent.parent.parent.add_pantry_item(root)
            

    MDCardSwipeFrontBox:
        OneLineListItem:
            id: content
            text: root.text
            icon: root.icon
            _no_ripple_effect: True

        RightCheckBox:




<dialog_content>
    
    quantity:quantity

    orientation:"vertical"
    spaceing: "12dp"
    size_hint_y: None
    height: "120dp"
    
    MDLabel:
        text: "Does this item expire?"
        valign: "top"

    MDRaisedButton:
        text: "Select an expiration date"
        pos_hint: {'center_x': .5, 'center_y': .5}
        on_release: app.sm.get_screen("window2").show_date_picker()
    
    MDTextField:
        id: quantity
        input_filter: 'int'
        hint_text: "Quantity"
        helper_text: "Default:1"
        helper_text_mode: "persistent"
        
        #color_mode: 'custom'
        #line_color_focus: 0, 1, 0, 1



<Check@MDCheckbox>:
    group: 'group'
    size_hint: None, None
    size: dp(48), dp(48) #48